#!/bin/bash
#PBS -j oe 
#PBS -l nodes=1:ppn=24
#PBS -q batch
#PBS -l walltime=240:60:00
cd $PBS_O_WORKDIR
NPROCS=`wc -l < $PBS_NODEFILE`
cat $PBS_NODEFILE > nodefile
#Run the parallel MPI executable a.out
date >> $HOME/arun.txt
pwd >> $HOME/arun.txt
echo This job has allocated $NPROCS $PBS_NODEFILE >> $HOME/arun.txt
#export  VASP=~/soft/vasp.5.4.4/bin/vasp_std
export  VASP=~/soft/vasp.5.4.4/bin/vasp_ncl
NPROCS=`wc -l < $PBS_NODEFILE`
mpirun -np $NPROCS $VASP> output
