#!/bin/bash
#PBS -j oe 
#PBS -l nodes=1:ppn=32
#PBS -q batch 
#PBS -l walltime=240:60:00
cd $PBS_O_WORKDIR
NPROCS=`wc -l < $PBS_NODEFILE`
cat $PBS_NODEFILE > nodefile
#Run the parallel MPI executable a.out
echo This job has allocated $NPROCS $PBS_NODEFILE >> $HOME/arun.txt
date >> $HOME/arun.txt
pwd >> $HOME/arun.txt
NPROCS=`wc -l < $PBS_NODEFILE`
export wann_tools=/home/wzw/soft/wannier_tools-2.5.1/bin/wt.x
cd $PBS_O_WORKDIR
mpirun -np $NPROCS $wann_tools< wt.in 
